// SPDX-License-Identifier: GPL-3.0-only

// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Illegal-0]
	_ = x[EOF-1]
	_ = x[Semi-2]
	_ = x[Ident-3]
	_ = x[Int-4]
	_ = x[String-5]
	_ = x[StringBeg-6]
	_ = x[StringCont-7]
	_ = x[StringEnd-8]
	_ = x[LInterp-9]
	_ = x[RInterp-10]
	_ = x[Import-11]
	_ = x[Let-12]
	_ = x[Func-13]
	_ = x[Step-14]
	_ = x[Struct-15]
	_ = x[Enum-16]
	_ = x[For-17]
	_ = x[In-18]
	_ = x[If-19]
	_ = x[Else-20]
	_ = x[Return-21]
	_ = x[True-22]
	_ = x[False-23]
	_ = x[None-24]
	_ = x[Self-25]
	_ = x[Plus-26]
	_ = x[Minus-27]
	_ = x[Star-28]
	_ = x[Slash-29]
	_ = x[Percent-30]
	_ = x[Eq-31]
	_ = x[Neq-32]
	_ = x[Lt-33]
	_ = x[Gt-34]
	_ = x[Leq-35]
	_ = x[Geq-36]
	_ = x[And-37]
	_ = x[Or-38]
	_ = x[Not-39]
	_ = x[Assign-40]
	_ = x[Colon-41]
	_ = x[Dot-42]
	_ = x[Question-43]
	_ = x[LBrace-44]
	_ = x[RBrace-45]
	_ = x[LBrack-46]
	_ = x[RBrack-47]
	_ = x[LParen-48]
	_ = x[RParen-49]
	_ = x[Comma-50]
}

const _Kind_name = "IllegalEOFSemiIdentIntStringStringBegStringContStringEndLInterpRInterpImportLetFuncStepStructEnumForInIfElseReturnTrueFalseNoneSelfPlusMinusStarSlashPercentEqNeqLtGtLeqGeqAndOrNotAssignColonDotQuestionLBraceRBraceLBrackRBrackLParenRParenComma"

var _Kind_index = [...]uint8{0, 7, 10, 14, 19, 22, 28, 37, 47, 56, 63, 70, 76, 79, 83, 87, 93, 97, 100, 102, 104, 108, 114, 118, 123, 127, 131, 135, 140, 144, 149, 156, 158, 161, 163, 165, 168, 171, 174, 176, 179, 185, 190, 193, 201, 207, 213, 219, 225, 231, 237, 242}

func (i Kind) String() string {
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
