// SPDX-License-Identifier: GPL-3.0-only

// Code generated by "stringer -type=ActionKind"; DO NOT EDIT.

package event

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActionStarted-0]
	_ = x[ActionFinished-1]
}

const _ActionKind_name = "ActionStartedActionFinished"

var _ActionKind_index = [...]uint8{0, 13, 27}

func (i ActionKind) String() string {
	if i >= ActionKind(len(_ActionKind_index)-1) {
		return "ActionKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActionKind_name[_ActionKind_index[i]:_ActionKind_index[i+1]]
}
