// SPDX-License-Identifier: GPL-3.0-only

// Code generated by "stringer -type=Chattiness"; DO NOT EDIT.

package event

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Subtle-0]
	_ = x[Reserved-1]
	_ = x[Normal-2]
	_ = x[Chatty-3]
	_ = x[Yappy-4]
}

const _Chattiness_name = "SubtleReservedNormalChattyYappy"

var _Chattiness_index = [...]uint8{0, 6, 14, 20, 26, 31}

func (i Chattiness) String() string {
	if i >= Chattiness(len(_Chattiness_index)-1) {
		return "Chattiness(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Chattiness_name[_Chattiness_index[i]:_Chattiness_index[i+1]]
}
