// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package event

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EngineStarted-0]
	_ = x[EngineFinished-1]
	_ = x[PlanStarted-2]
	_ = x[PlanFinished-3]
	_ = x[UnitPlanned-4]
	_ = x[ActionStarted-5]
	_ = x[ActionFinished-6]
	_ = x[OpCheckStarted-7]
	_ = x[OpChecked-8]
	_ = x[OpExecuteStarted-9]
	_ = x[OpExecuted-10]
	_ = x[DiagnosticRaised-11]
}

const _Kind_name = "EngineStartedEngineFinishedPlanStartedPlanFinishedUnitPlannedActionStartedActionFinishedOpCheckStartedOpCheckedOpExecuteStartedOpExecutedDiagnosticRaised"

var _Kind_index = [...]uint8{0, 13, 27, 38, 50, 61, 74, 88, 102, 111, 127, 137, 153}

func (i Kind) String() string {
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
