// SPDX-License-Identifier: GPL-3.0-only

// Code generated by "stringer -type=OpKind"; DO NOT EDIT.

package event

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpCheckStarted-0]
	_ = x[OpChecked-1]
	_ = x[OpExecuteStarted-2]
	_ = x[OpExecuted-3]
}

const _OpKind_name = "OpCheckStartedOpCheckedOpExecuteStartedOpExecuted"

var _OpKind_index = [...]uint8{0, 14, 23, 39, 49}

func (i OpKind) String() string {
	if i >= OpKind(len(_OpKind_index)-1) {
		return "OpKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpKind_name[_OpKind_index[i]:_OpKind_index[i+1]]
}
