// Code generated by "stringer -type=PlanKind"; DO NOT EDIT.

package event

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PlanStarted-0]
	_ = x[PlanFinished-1]
	_ = x[StepPlanned-2]
	_ = x[PlanProduced-3]
}

const _PlanKind_name = "PlanStartedPlanFinishedStepPlannedPlanProduced"

var _PlanKind_index = [...]uint8{0, 11, 23, 34, 46}

func (i PlanKind) String() string {
	if i >= PlanKind(len(_PlanKind_index)-1) {
		return "PlanKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PlanKind_name[_PlanKind_index[i]:_PlanKind_index[i+1]]
}
