// Code generated by "stringer -type=Scope"; DO NOT EDIT.

package event

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ScopeEngine-0]
	_ = x[ScopePlan-1]
	_ = x[ScopeAction-2]
	_ = x[ScopeOp-3]
}

const _Scope_name = "ScopeEngineScopePlanScopeActionScopeOp"

var _Scope_index = [...]uint8{0, 11, 20, 31, 38}

func (i Scope) String() string {
	if i >= Scope(len(_Scope_index)-1) {
		return "Scope(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Scope_name[_Scope_index[i]:_Scope_index[i+1]]
}
